# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crest_app', '0003_auto_20160317_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_character_id', models.BigIntegerField(default=0)),
                ('_character_name', models.CharField(default=b'', max_length=128)),
                ('_corporation_name', models.CharField(default=b'', max_length=128)),
                ('_alliance_name', models.CharField(default=b'', max_length=128)),
                ('_alliance_id', models.BigIntegerField(default=0)),
                ('_corporation_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='eveuser',
            name='_alliance_id',
        ),
        migrations.RemoveField(
            model_name='eveuser',
            name='_alliance_name',
        ),
        migrations.RemoveField(
            model_name='eveuser',
            name='_character_id',
        ),
        migrations.RemoveField(
            model_name='eveuser',
            name='_character_name',
        ),
        migrations.RemoveField(
            model_name='eveuser',
            name='_corporation_id',
        ),
        migrations.RemoveField(
            model_name='eveuser',
            name='_corporation_name',
        ),
        migrations.AddField(
            model_name='eveuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
