# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crest_app', '0004_auto_20160317_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveuserprofile',
            name='profile_created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 17, 13, 48, 54, 809583, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveuserprofile',
            name='profile_updated_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 3, 17, 13, 48, 58, 609530, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
