# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crest_app', '0005_auto_20160317_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveuserprofile',
            name='profile_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eveuserprofile',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
