# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [(b'market', '0001_initial'), (b'market', '0002_auto_20160321_1349'), (b'market', '0003_auto_20160321_1421'), (b'market', '0004_auto_20160321_1432'), (b'market', '0005_auto_20160321_1435'), (b'market', '0006_auto_20160321_1436'), (b'market', '0007_auto_20160321_1445'), (b'market', '0008_auto_20160321_1453'), (b'market', '0009_cartitem'), (b'market', '0010_auto_20160329_1721')]

    initial = True

    dependencies = [
        ('crest_app', '0001_squashed_0006_auto_20160317_1351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvType',
            fields=[
                ('typeID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('mass', models.FloatField()),
                ('volume', models.FloatField()),
                ('capacity', models.FloatField()),
                ('portionSize', models.FloatField()),
                ('raceID', models.IntegerField()),
                ('basePrice', models.FloatField()),
                ('published', models.SmallIntegerField(verbose_name='Whether or not this item has been published')),
                ('iconID', models.FloatField()),
                ('soundID', models.IntegerField()),
                ('graphicID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('groupID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryID', models.IntegerField()),
                ('groupName', models.CharField(max_length=128)),
                ('iconID', models.IntegerField()),
                ('useBasePrice', models.SmallIntegerField()),
                ('anchored', models.SmallIntegerField()),
                ('anchorable', models.SmallIntegerField()),
                ('fittableNonSingleton', models.SmallIntegerField()),
                ('published', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemMarketGroup',
            fields=[
                ('marketGroupID', models.IntegerField(primary_key=True, serialize=False)),
                ('parentGroupID', models.IntegerField()),
                ('marketGroupName', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('iconID', models.IntegerField()),
                ('hasTypes', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='invtype',
            name='itemgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ItemGroup', verbose_name='The related Item Group (groupID)'),
        ),
        migrations.AddField(
            model_name='invtype',
            name='itemmarketgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ItemMarketGroup', verbose_name='The related market Group (marketGroupID)'),
        ),
        migrations.AlterModelOptions(
            name='invtype',
            options={'verbose_name': 'Item Type', 'verbose_name_plural': 'Item Types'},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'verbose_name': 'Item Group', 'verbose_name_plural': 'Item Groups'},
        ),
        migrations.AlterModelOptions(
            name='itemmarketgroup',
            options={'verbose_name': 'Market Group', 'verbose_name_plural': 'Market Groups'},
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='parentGroupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ItemMarketGroup', verbose_name='The parent market group'),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='itemgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ItemGroup', verbose_name='Related Item Group (groupID)'),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='itemmarketgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.ItemMarketGroup', verbose_name='Related market Group (marketGroupID)'),
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='parentGroupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.ItemMarketGroup', verbose_name='Parent market group'),
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='parentGroupID',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.ItemMarketGroup', verbose_name='Parent market group'),
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='parentGroupID',
            field=models.IntegerField(verbose_name='Parent market group id'),
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='parentGroupID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent market group id'),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='graphicID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='iconID',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='soundID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='iconID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='iconID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='raceID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='How many of that item')),
                ('invtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.InvType', verbose_name='Related Item Type')),
                ('eveuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crest_app.EveUserProfile', verbose_name='Related EVE User Profile')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
