# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invtype',
            options={'verbose_name': 'Item Type', 'verbose_name_plural': 'Item Types'},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'verbose_name': 'Item Group', 'verbose_name_plural': 'Item Groups'},
        ),
        migrations.AlterModelOptions(
            name='itemmarketgroup',
            options={'verbose_name': 'Market Group', 'verbose_name_plural': 'Market Groups'},
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='parentGroupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ItemMarketGroup', verbose_name='The parent market group'),
        ),
    ]
