# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20160321_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invtype',
            name='graphicID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='iconID',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invtype',
            name='soundID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='iconID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemmarketgroup',
            name='iconID',
            field=models.IntegerField(null=True),
        ),
    ]
