# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20160321_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invtype',
            name='raceID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
