# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crest_app', '0006_auto_20160317_1351'),
        ('market', '0009_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='eveuser',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 29, 17, 21, 27, 876111, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='crest_app.EveUserProfile', verbose_name='Related EVE User Profile'),
            preserve_default=False,
        ),
    ]
